name: Run Instagram Scraper Every 2 Hours

on:
  schedule:
    - cron: '0 */2 * * *'  # Runs every 2 hours
  workflow_dispatch:       # Allows manual run from GitHub

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        pip install requests psycopg2-binary cloudinary selenium

    - name: Set up Chrome
      uses: browser-actions/setup-chrome@v1

    - name: Run scraper
      run: |
        google-chrome --version
        python scrapping_insta_with_picture2.py
